/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.trabalho1;

/**
 *
 * @author junio
 */
public class Calculadora extends javax.swing.JPanel {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        grupo.add(soma);
        grupo.add(multiplicacao);
        grupo.add(divisao);
        grupo.add(subtracao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        NewjPanel = new javax.swing.JPanel();
        Painel = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        texto1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        texto2 = new javax.swing.JTextField();
        soma = new javax.swing.JRadioButton();
        multiplicacao = new javax.swing.JRadioButton();
        divisao = new javax.swing.JRadioButton();
        subtracao = new javax.swing.JRadioButton();
        input = new javax.swing.JButton();

        javax.swing.GroupLayout NewjPanelLayout = new javax.swing.GroupLayout(NewjPanel);
        NewjPanel.setLayout(NewjPanelLayout);
        NewjPanelLayout.setHorizontalGroup(
            NewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        NewjPanelLayout.setVerticalGroup(
            NewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("valor1");

        texto1.setText("Insira o valor");
        texto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto1ActionPerformed(evt);
            }
        });

        jLabel2.setText("valor2");

        texto2.setText("Insira o valor");

        soma.setText("soma");

        multiplicacao.setText("multiplicação");

        divisao.setText("divisão");

        subtracao.setText("subtração");

        input.setText("Ok");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texto1)
                            .addComponent(texto2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(soma)
                                    .addComponent(divisao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(input))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subtracao)
                                    .addComponent(multiplicacao))))
                        .addContainerGap(173, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(121, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(multiplicacao)
                        .addGap(18, 18, 18)
                        .addComponent(subtracao)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(divisao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(soma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(texto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(input, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(Painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void texto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto1ActionPerformed
       try {
        // Leitura dos valores dos campos de texto
        double valor1 = Double.parseDouble(texto1.getText());
        double valor2 = Double.parseDouble(texto2.getText());
        double resultado = 0;

        // Verificação de qual operação foi selecionada
        if (soma.isSelected()) {
            resultado = valor1 + valor2;
        } else if (subtracao.isSelected()) {
            resultado = valor1 - valor2;
        } else if (multiplicacao.isSelected()) {
            resultado = valor1 * valor2;
        } else if (divisao.isSelected()) {
            if (valor2 != 0) {
                resultado = valor1 / valor2;
            } else {
                Painel.showMessageDialog(this, "Erro: Divisão por zero não é permitida.", "Erro", Painel.ERROR_MESSAGE);
                return;
            }
        } else {
            Painel.showMessageDialog(this, "Por favor, selecione uma operação.", "Aviso", Painel.WARNING_MESSAGE);
            return;
        }

        // Exibe o resultado em uma MessageDialog
        Painel.showMessageDialog(this, "Resultado: " + resultado, "Resultado", Painel.INFORMATION_MESSAGE);
    } catch (NumberFormatException e) {
        Painel.showMessageDialog(this, "Erro: Insira valores numéricos válidos.", "Erro", Painel.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_texto1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NewjPanel;
    private javax.swing.JOptionPane Painel;
    private javax.swing.JRadioButton divisao;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JButton input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton multiplicacao;
    private javax.swing.JRadioButton soma;
    private javax.swing.JRadioButton subtracao;
    private javax.swing.JTextField texto1;
    private javax.swing.JTextField texto2;
    // End of variables declaration//GEN-END:variables
}
